{ ... }:
{
  imports = [
    ./aerc.nix
    ./alacritty.nix
    ./beets.nix
    ./btop.nix
    ./cava.nix
    ./cmus.nix
    ./dircolors.nix
    ./direnv.nix
    ./fish.nix
    ./foot.nix
    ./fzf.nix
    ./gpg.nix
    ./helix.nix
    ./lazygit.nix
    ./mpv.nix
    ./newsboat.nix
    ./password-store.nix
    ./qutebrowser.nix
    ./rmpc.nix
    ./swaylock.nix
    ./vifm.nix
    ./waybar.nix
    ./yazi.nix
    ./zathura.nix
    ./zk.nix
    ./zsh.nix
  ];
}
